services:
  - type: web
    name: mentornest
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "18000000"
      - key: JWT_REFRESH_EXPIRATION
        value: "604800000"
      - key: BASE_URL
        value: https://mentornest.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
